/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public static Logger logger = LogManager.getLogger();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.info(new App().getGreeting());
    }
}
